#!/bin/bash
# Gather project status from multiple sources
echo "=== RESUME STATE ==="
cat .claude/state/resume.md 2>/dev/null || echo "No resume file"
echo ""
echo "=== GIT STATE ==="
git status --short 2>/dev/null || echo "Not a git repo"
echo ""
echo "=== RECENT COMMITS ==="
git log --oneline -5 2>/dev/null || echo "No commits"
echo ""
echo "=== CURRENT BRANCH ==="
git branch --show-current 2>/dev/null || echo "Unknown"
echo ""
echo "=== DOCUMENTATION ==="
ls -la docs/*.md 2>/dev/null || echo "No docs yet"
echo ""
echo "=== HANDOVERS ==="
ls -la .claude/handover/*.md 2>/dev/null || echo "No handover files"
echo ""
echo "=== STATE FILES ==="
ls -la .claude/state/*.md 2>/dev/null || echo "No state files"
